
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (1, 'Peso', 10.14, 'PHP');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (2, 'Rupee', 0.8, 'PKR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (3, 'Dong', 11.59, 'VND');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (4, 'Euro', 18.4, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (5, 'Som', 15.65, 'UZS');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (6, 'Peso', 2.43, 'PHP');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (7, 'Yuan Renminbi', 5.57, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (8, 'Yuan Renminbi', 18.06, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (9, 'Franc', 7.88, 'XOF');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (10, 'Shekel', 8.26, 'ILS');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (11, 'Real', 16.32, 'BRL');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (12, 'Zloty', 9.79, 'PLN');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (13, 'Yuan Renminbi', 16.3, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (14, 'Yuan Renminbi', 16.32, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (15, 'Ruble', 5.62, 'BYR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (16, 'Euro', 4.5, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (17, 'Shekel', 3.02, 'ILS');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (18, 'Afghani', 5.6, 'AFN');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (19, 'Rupiah', 7.97, 'IDR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (20, 'Dram', 7.31, 'AMD');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (21, 'Krona', 1.06, 'SEK');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (22, 'Euro', 4.63, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (23, 'Yuan Renminbi', 6.18, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (24, 'Yuan Renminbi', 23.24, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (25, 'Yuan Renminbi', 7.2, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (26, 'Rupiah', 22.58, 'IDR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (27, 'Krona', 12.11, 'SEK');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (28, 'Rupiah', 23.97, 'IDR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (29, 'Euro', 25.44, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (30, 'Hryvnia', 6.67, 'UAH');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (31, 'Yuan Renminbi', 3.03, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (32, 'Dram', 16.97, 'AMD');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (33, 'Yuan Renminbi', 7.22, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (34, 'Ariary', 16.0, 'MGA');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (35, 'Bolivar', 1.81, 'VEF');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (36, 'Zloty', 20.68, 'PLN');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (37, 'Yen', 18.9, 'JPY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (38, 'Euro', 1.97, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (39, 'Real', 0.81, 'BRL');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (40, 'Peso', 18.91, 'MXN');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (41, 'Real', 5.61, 'BRL');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (42, 'Euro', 13.61, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (43, 'Yuan Renminbi', 14.99, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (44, 'Cedi', 20.43, 'GHS');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (45, 'Yuan Renminbi', 5.12, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (46, 'Euro', 12.67, 'EUR');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (47, 'Baht', 17.59, 'THB');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (48, 'Yuan Renminbi', 13.21, 'CNY');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (49, 'Hryvnia', 16.46, 'UAH');
insert into currencys (currency_id, currency, exchange_rate, currency_code) values (50, 'Rupiah', 16.57, 'IDR');
