
insert into inventorygroups (inventorygroup_id, inventorygroup) values (1, 'Marketing');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (2, 'Engineering');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (3, 'Product Management');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (4, 'Research and Development');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (5, 'Support');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (6, 'Legal');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (7, 'Sales');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (8, 'Legal');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (9, 'Marketing');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (10, 'Engineering');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (11, 'Engineering');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (12, 'Legal');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (13, 'Training');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (14, 'Product Management');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (15, 'Services');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (16, 'Research and Development');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (17, 'Business Development');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (18, 'Sales');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (19, 'Marketing');
insert into inventorygroups (inventorygroup_id, inventorygroup) values (20, 'Product Management');
