
insert into positions (position_id, position) values (1, 'Human Resources');
insert into positions (position_id, position) values (2, 'Accounting');
insert into positions (position_id, position) values (3, 'Marketing');
insert into positions (position_id, position) values (4, 'Marketing');
insert into positions (position_id, position) values (5, 'Support');
insert into positions (position_id, position) values (6, 'Legal');
insert into positions (position_id, position) values (7, 'Product Management');
insert into positions (position_id, position) values (8, 'Legal');
insert into positions (position_id, position) values (9, 'Marketing');
insert into positions (position_id, position) values (10, 'Engineering');
insert into positions (position_id, position) values (11, 'Support');
insert into positions (position_id, position) values (12, 'Product Management');
insert into positions (position_id, position) values (13, 'Research and Development');
insert into positions (position_id, position) values (14, 'Product Management');
insert into positions (position_id, position) values (15, 'Legal');
insert into positions (position_id, position) values (16, 'Research and Development');
insert into positions (position_id, position) values (17, 'Sales');
insert into positions (position_id, position) values (18, 'Services');
insert into positions (position_id, position) values (19, 'Services');
insert into positions (position_id, position) values (20, 'Business Development');
insert into positions (position_id, position) values (21, 'Legal');
insert into positions (position_id, position) values (22, 'Research and Development');
insert into positions (position_id, position) values (23, 'Accounting');
insert into positions (position_id, position) values (24, 'Legal');
insert into positions (position_id, position) values (25, 'Support');
